Add group parameter (#5)
* add `group_id` parameter

- removed an old `username` parameter that was missed
- changed `user id` to `user_id`
- changed `number of common interests` to `common interest count`
- added some type hints
- removed `show_doc` from notebook that was used for preview

* `list[str]` to `List[str]` in `show_interests()`

- CI tests failed
- error:
https://github.com/batmanscode/MatchDB/actions/runs/4072684027/jobs/7015716975

```python
    138 def show_interests(user_id: str,
    139                    database_name: str,
    140                    project_key: str = "PROJECT_KEY" # the environment variable name where your Deta project key is stored
--> 141                   ) -> list[str]:
    143     "Gets a list of interests for a given user. Uses `find_by_userid`."
    145     return find_by_userid(user_id, database_name, project_key)["interests"]

TypeError: 'type' object is not subscriptable
```